draw_set_alpha(whitefade);
draw_set_color(c_white);
draw_rectangle(0, 0, obj_screensizer.displayWidth, obj_screensizer.displayHeight, false);
draw_set_color(c_white);
draw_set_alpha(1);
draw_set_alpha(blackfade);
draw_set_color(c_black);
draw_rectangle(0, 0, obj_screensizer.displayWidth, obj_screensizer.displayHeight, false);
draw_set_color(c_white);
draw_set_alpha(1);
