obj_player.state = -4;
worldNames = ["Lunch Hour", "Happy Holidays", "Privacy"];
levels = [];
var _world1 = [[tutorial_1, "tutorial", "A", "Tutorial"], [mangrove_1, "forest", "A", "Waybackyard"], [shell_1, "shell", "A", "Shell City"], [beach_1, "beach", "A", "Fruitcup Coast"]];
var _world2 = [[castle_1, "castle", "A", "Castle Pumpkinstein"], [kingdom_1, "kingdom", "A", "Snowcone Kingdom"]];
array_push(levels, _world1);
array_push(levels, _world2);
selectedWorld = 0;
selectedLevel = 0;
potableIndex = 0;
